# Generated by Django 4.1 on 2024-05-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_movie_actors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="cinema_hall",
        ),
    ]
